name: Deploy Kika to AWS Elastic Beanstalk (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EB Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, zip
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy .env.pipeline to .env
        run: cp .env.pipeline .env

      - name: Set Permissions (storage & bootstrap cache)
        run: |
          chmod -R 775 storage bootstrap/cache
          sudo chown -R $USER:www-data storage bootstrap/cache

      - name: Zip source for deployment
        run: zip -r kika-app-code.zip . -x "*.git*" "node_modules/*" "tests/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: kika-prod-laravel-app-new
          environment_name: kika-prod-laravel-app-new-env
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          version_label: kika-app-prod_${{ github.sha }}
          existing_bucket_name: kika-app-code-upload-pipeline
          deployment_package: kika-app-code.zip

      - name: Generate Laravel Passport Keys on EB
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_PROD_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PROD_SSH_PRIVATE_KEY }}
          script: |
            cd /var/app/current
            sudo chown -R webapp:webapp storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            if [ ! -f storage/oauth-private.key ]; then
              sudo -u webapp php artisan passport:keys --force
              sudo chmod 600 storage/oauth-*.key
              sudo chown webapp:webapp storage/oauth-*.key
            fi
            
            sudo service php-fpm restart
            sudo service nginx restart
